# Generated by Django 5.1 on 2024-09-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centroApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
