# Generated by Django 5.0.6 on 2024-07-07 14:23

import centroApp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centroApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', centroApp.models.UserManager()),
            ],
        ),
    ]
