# Generated by Django 5.0.6 on 2024-07-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroApp', '0004_remove_product_imageurl_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
