# Generated by Django 5.1 on 2024-09-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroApp', '0005_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.FloatField(),
        ),
    ]
