# Generated by Django 5.1 on 2024-09-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroApp', '0006_alter_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
