# Generated by Django 5.1 on 2024-08-16 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroApp', '0008_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='userName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
