# Generated by Django 5.1 on 2024-09-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroApp', '0009_product_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
