# Generated by Django 5.1 on 2024-09-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroApp', '0009_premiummembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiummembership',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
