# Generated by Django 5.1 on 2024-09-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroApp', '0010_alter_premiummembership_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiummembership',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
