# Generated by Django 4.1.7 on 2024-11-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroApp', '0015_product_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
